Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/biokeminfo/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
payload6 = {'query': 'accession:Q7RTY8', 'format': 'fasta'}
result6 = requests.get(BASE + KB_ENDPOINT, params=payload6)
# print(result6.text)

f = open('izhod/uniprot-sample_output.fasta', 'w')
f.write(result6.text)
f.close()

# odpremo in preberemo datoteko
f = open('izhod/uniprot-sample_output.fasta', 'r')
print(f.read())

# izpi≈°emo vsebino prebrane datoteke z uporabo BioPythona
from Bio import SeqIO
for seq_record in SeqIO.parse('izhod/uniprot-sample_output.fasta', 'fasta'):
    print(seq_record.id)   # izpi≈°emo ID
    print(repr(seq_record.seq))   # izpi≈°emo objekt
    print(seq_record.seq)   # izpi≈°emo samo zaporedje
    print(len(seq_record))   # izpi≈°emo dol≈æino zaporedja
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[9], line 14[0m
[1;32m     11[0m [38;5;28mprint[39m(f[38;5;241m.[39mread())
[1;32m     13[0m [38;5;66;03m# izpi≈°emo vsebino prebrane datoteke z uporabo BioPythona[39;00m
[0;32m---> 14[0m [38;5;28;01mfrom[39;00m [38;5;21;01mBio[39;00m [38;5;28;01mimport[39;00m SeqIO
[1;32m     15[0m [38;5;28;01mfor[39;00m seq_record [38;5;129;01min[39;00m SeqIO[38;5;241m.[39mparse([38;5;124m'[39m[38;5;124mizhod/uniprot-sample_output.fasta[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mfasta[39m[38;5;124m'[39m):
[1;32m     16[0m     [38;5;28mprint[39m(seq_record[38;5;241m.[39mid)   [38;5;66;03m# izpi≈°emo ID[39;00m

[0;31mModuleNotFoundError[0m: No module named 'Bio'
ModuleNotFoundError: No module named 'Bio'

